print(list(range(5)))           # (a)
print(list(range(5, 10)))       # (b)
print(list(range(5, 20, 3)))    # (c)
print(list(range(20, 5, -1)))   # (d)
print(list(range(20, 5, -3)))   # (e)
print(list(range(10, 5)))       # (f)
print(list(range(0)))           # (g)
print(list(range(10, 101, 10))) # (h)
print(list(range(10, -1, -1)))  # (i)
print(list(range(-3, 4)))       # (j)
print(list(range(0, 10, 1)))    # (k)